### ISSUE TITLE
Updated toml spec

### ISSUE THREAD

**Issue by rkrishnasanka** [getinstachip/vpm#13]
# Define the full(ish) toml spec

## Motivation

The current minimal spec approach is dangerous for HDL / hardware design. Hardware designs are so much more harder to debug and hence having a tight control on how we are specifying dependencies is super important.

> Why are we doing this? What use cases does it support?

The current version of the .toml leaves a lot of fields open custom interpretation so having all these fields defined is going to be important going forward.

## Detailed design

Here is the fully defined .toml spec (we can discuss modifications)

**toml**

```toml
[tool.vpm.library]
name = "krishna_library"
version = "0.3.5"
description = "Most important library in the world"
authors = ["Radhakrishna Sanka"]
license = [
    {type="BSD-3-Clause", source=["folder_with_artifacts/*.whatever"]},
    {type="CC-4", source=["folder_with_artifacts/*.whatever"]},
    {type="Copyright@RandomStuffyCompany", source=["whatever"]},
]

include = [
    "folder_with_modules/*",
]

[tool.vpm.docs]
docspath="./not-standard-docs-path"
futuredocsoption1=true
futuredocsoption2=false

[tool.vpm.dependencies]
"https://github.com/ZipCPU/zipcpu" = {"version"="1.1.1", alias="unique_library_name", modules = ["m1", "m2"], branch="not-main", commit="hashwhenwedontgivesemver"}
"https://github.com/ZipCPU/zipcpu" = {"version"="1.1.1", alias="unique_library_name", modules = ["m1", "m2"], branch="not-main", commit="hashwhenwedontgivesemver"}

[tool.vpm.dev-dependencies]
"./path/to/file" = {"version"="1.1.1", alias="unique_library_name", modules = ["m1", "m2"], branch="not-main", commit="hashwhenwedontgivesemver"}

[tool.vpm.config]
futureconfigparam1=true
futureconfigparam2=false


```

**.toml.lock**
```toml
[tool.vpm.library]
name = "krishna_library"
version = "0.3.5"
description = "Most important library in the world"
authors = ["Radhakrishna Sanka"]
license = [
    {type="BSD-3-Clause", source=["folder_with_artifacts/*.whatever"]},
    {type="CC-4", source=["folder_with_artifacts/*.whatever"]},
    {type="Copyright@RandomStuffyCompany", source=["whatever"]},
]

include = [
    "folder_with_modules/*",
]


[tool.vpm.config]
futureconfigparam1=true
futureconfigparam2=false

[tool.vpm.docs]
docspath="./not-standard-docs-path"
futuredocsoption1=true
futuredocsoption2=false

[tool.vpm.lock-dependencies]
"https://github.com/ZipCPU/zipcpu" = {"version"="1.1.1", alias="unique_library_name", modules = ["m1", "m2"], branch="not-main", commit="hash"}
"https://github.com/ZipCPU/zipcpu" = {"version"="1.1.1", alias="unique_library_name", modules = ["m1", "m2"], branch="not-main", commit="hash"}


```

Notes about lock dependencies:
-  All dev and non dev dependencies are put into the lock-dependencies
- We copy the rest of the params for posterity / archival purposes
- We keep the "version" only for data tracking purposes (if we need it in the future or if the user needs to figure out what version its connected to). All dependency computations happen on the exact hash only
- All the dependencies need to be placed linearly, do the recursive DFS of the dependency tree and just put everything as a single list, there is no need to track that in the .lock file since all the installations will be saved linearly. 
- The lock file generation should error out when multiple dependencies have the same unique library name or if theres no way to distinguish them
- TBA

### Technical Background

TBA

### Implementation

TBA

## Drawbacks

TBA

## Alternatives

> What other designs have been considered? What is the impact of not doing this?

TBA

> This section could also include prior art, that is, how other frameworks in the
> same domain have solved this problem differently.

A lot of this has been shamelessly copied form https://python-poetry.org/

## Unresolved questions

> Optional, but suggested for first drafts. What parts of the design are still TBD?
